name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: portfolio

      - name: Build project
        run: npm run build
        working-directory: portfolio
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.KNOWN_HOSTS}}
          
      - name: Deploy frontend to DigitalOcean
        run: |
          rsync -avz --delete ./portfolio/build/ root@${{ secrets.DROPLET_IP }}:/var/www/portfolio/

      - name: Restart backend with PM2
        run: |
          ssh root@${{ secrets.DROPLET_IP }} 'cd /root/portfolio/portfolio/server && pm2 restart portfolio-backend --update-env'
