name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: portfolio

      - name: Build project
        run: npm run build
        working-directory: portfolio

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: ${{secrets.KNOWN_HOSTS}}

      - name: Deploy frontend to DigitalOcean
        run: |
          rsync -avz --delete ./portfolio/build/ root@${{ secrets.DROPLET_IP }}:/var/www/zakariae.live/html/

      - name: Deploy Flask backend to DigitalOcean
        run: |
          rsync -avz --delete ./portfolio/server/ root@${{ secrets.DROPLET_IP }}:/var/www/portfolio/portfolio/server/

      - name: Update environment and restart services
        run: |
          ssh root@${{ secrets.DROPLET_IP }} '
            cd /var/www/portfolio/portfolio/server &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" > .env &&
            pm2 restart flask-backend &&
            sudo systemctl reload nginx
          '
